DROP DATABASE IF EXISTS PTTP;

CREATE DATABASE PTTP;
USE PTTP;


-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'book'
--
-- ---

DROP TABLE IF EXISTS `BOOK`;

CREATE TABLE `BOOK` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL,
  `AUTHOR` TEXT(1000),
  `RELEASE_DATE` DATE,
  `PUBLISHER` VARCHAR(255),
  `PRICE` FLOAT DEFAULT NULL,
  `AVAILABLE` TINYINT(1) DEFAULT NULL,
  `MOBI_FORMAT` TINYINT(1) DEFAULT NULL,
  `EPUB_FORMAT` TINYINT(1) DEFAULT NULL,
  `MP3_FORMAT` TINYINT(1) DEFAULT NULL,
  `DESCRIPTION` TEXT(5000) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'USERS'
--
-- ---

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `LOGIN` VARCHAR(50) NOT NULL DEFAULT 'NULL',
  `PASSWORD` VARCHAR(50) NOT NULL DEFAULT 'NULL',
  `MONEY` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'GENRES'
--
-- ---

DROP TABLE IF EXISTS `GENRES`;

CREATE TABLE `GENRES` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `GENRE` VARCHAR(255) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'CART'
--
-- ---

DROP TABLE IF EXISTS `CART`;

CREATE TABLE `CART` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `OWNER` INTEGER,
  `ITEM` INTEGER,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'CATALOGUE'
--
-- ---

DROP TABLE IF EXISTS `CATALOGUE`;

CREATE TABLE `CATALOGUE` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `BOOK` INTEGER NOT NULL,
  `GENRE` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'STORAGE'
--
-- ---

DROP TABLE IF EXISTS `STORAGE`;

CREATE TABLE `STORAGE` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `BOOK` INTEGER DEFAULT NULL,
  `AQ_DATE` DATE DEFAULT NULL,
  `OWNER` INTEGER DEFAULT NULL,
  `EXP_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Foreign Keys
-- ---

ALTER TABLE `CART` ADD FOREIGN KEY (OWNER) REFERENCES `USERS` (`id`);
ALTER TABLE `CART` ADD FOREIGN KEY (ITEM) REFERENCES `BOOK` (`id`);
ALTER TABLE `CATALOGUE` ADD FOREIGN KEY (BOOK) REFERENCES `BOOK` (`id`);
ALTER TABLE `CATALOGUE` ADD FOREIGN KEY (GENRE) REFERENCES `GENRES` (`id`);
ALTER TABLE `STORAGE` ADD FOREIGN KEY (BOOK) REFERENCES `BOOK` (`id`);
ALTER TABLE `STORAGE` ADD FOREIGN KEY (OWNER) REFERENCES `USERS` (`id`);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `BOOK` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `USERS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `GENRES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CART` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CATALOGUE` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `STORAGE` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `BOOK` (`id`,`TITLE`,`AUTHOR`,`RELEASE_DATE`,`PUBLISHER`,`PRICE`,`AVAILABLE`,`MOBI_FORMAT`,`EPUB_FORMAT`,`MP3_FORMAT`,`DESCRIPTION`) VALUES
-- ('','','','','','','','','','','');
-- INSERT INTO `USERS` (`id`,`LOGIN`,`PASSWORD`,`MONEY`) VALUES
-- ('','','','');
-- INSERT INTO `GENRES` (`id`,`GENRE`) VALUES
-- ('','');
-- INSERT INTO `CART` (`id`,`OWNER`,`ITEM`) VALUES
-- ('','','');
-- INSERT INTO `CATALOGUE` (`id`,`BOOK`,`GENRE`) VALUES
-- ('','','');
-- INSERT INTO `STORAGE` (`id`,`BOOK`,`AQ_DATE`,`OWNER`,`EXP_DATE`) VALUES
-- ('','','','','');
